### ISSUE TITLE
Custom Cards or Card Designs

### ISSUE THREAD

**Issue by PascalS86** [Azure/LearnAI-Airlift#1]
# Custom Cards or Card Designs

Hi all,
I was doing this training and what is missing in my point of view is a look into Custom Cards as Bot Responses. We took a look in search result with azure search and bing search, but not in custom cards design. Do you think, it belongs to this training or is there another training already available?
Find reference in [docs.microsoft.com](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-rich-cards?view=azure-bot-service-4.0)

Greetings :)

**Comment by Rodrigossz** [comment]
Hi. It is not covered in this training.

**Comment by Rodrigossz** [comment]
Out of scope.
